The path for nftDetails' CodeUri should ./lambda/nftdetails instead of ./lambda/nftDetails Incorrect path will cause deploy error. Following is the error message:
Error: Unable to upload artifact nftDetails referenced by CodeUri parameter of nftDetails resource.
Parameter CodeUri of resource nftDetails refers to a file or folder that does not exist /home/ubuntu/environment/nft-access-control-lambda-authorizer/serverless/.aws-sam/build/nftDetails